name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore StringCalculator.sln

    - name: Build
      run: dotnet build StringCalculator.sln --no-restore --configuration Release

    - name: Execute unit tests
      run: dotnet test StringCalculator.sln --no-build --configuration Release --verbosity normal
